# site properties and page defaults
title: ParaFuGe Lab
subtitle: Parasite Functional Genetics Laboratory
description: We are a team of researchers interested in understanding how malaria parasites live and multiply within red blood cells. Our research focuses on identifying the critical functions of genes that these parasites rely on to survive in the bloodstream. We disrupt specific genes and closely study how this affects the parasite, and we do this at scale to speed up discoveries. These fascinating explorations take place at the School of Infection and Immunity, University of Glasgow.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: abhinay.ramaprasad@glasgow.ac.uk
  orcid: 0000-0001-9372-5526
  google-scholar: TsSM6-cAAAAJ
  github: a2g1n
  twitter: ab1nay
  bluesky: abhinay.bsky.social

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
