- id: doi:10.1101/2024.01.14.575607
  type: preprint
  publisher: bioRxiv
  description: This preprint introduces SHIFTiKO, a novel inducible gene knockout 
                system to study essential gene function at scale in **P. falciparum**.
  image: https://www.biorxiv.org/content/biorxiv/early/2024/01/15/2024.01.14.575607/F1.medium.gif
  buttons:
    - type: pdf
      text: Preprint
      link: https://www.biorxiv.org/content/10.1101/2024.01.14.575607v1.full.pdf
    - type: source
      text: Analysis
      link: https://zenodo.org/records/13839817
    - type: data
      text: Raw data
      link: https://zenodo.org/records/13839540
    - type: plasmid
      text: Plasmid maps
      link: https://zenodo.org/records/10547132
  tags:
    - SHIFTiKO
    - DiCre
    - method
