- id: doi:10.17504/protocols.io.eq2ly68begx9/v1
  type: protocols
  publisher: protocols.io
  title: Design strategy for DiCre-mediated inducible gene knockout in the malaria parasite
  description: This protocol describes a detailed strategy for inducibly knocking out a target gene in Plasmodium species using the Dimerisable Cre (DiCre) recombinase system, with a primary focus on *Plasmodium falciparum*.
  authors:
  - Anagha Rajesh Salvi
  - Abhinay Ramaprasad
  image: https://content.protocols.io/files/sg94cdmmp.jpg
  tags:
    - DiCre
    - protocols
  date: '2024-12-24'
  link: https://dx.doi.org/10.17504/protocols.io.eq2ly68begx9/v1

- id: doi:10.17504/protocols.io.n2bvjn9d5gk5/v1
  type: protocols
  publisher: protocols.io
  description: This protocol describes a one-pot GoldenGate assembly of a new dual-guide targeting plasmid (pCas9-Duo) expressing two distinct guide RNAs in order to enhance the chances of a successful Cas9-mediated modification at a target region in *Plasmodium falciparum*.
  image: https://protocols-files.s3.amazonaws.com/files/qssucdmmp.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJYFAX46LHRVQMGOA%2F20241225%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241225T210932Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=dba1d8be3cfcb7bcbca2e927c742f98fd0acb1918a526957262d5c80bcd543d5
  tags:
    - SHIFTiKO
    - DiCre
    - protocols

- id: doi:10.1101/2024.01.14.575607
  type: preprint
  publisher: bioRxiv
  description: This preprint introduces SHIFTiKO, a novel inducible gene knockout 
                system to study essential gene function at scale in *P. falciparum*.
  image: https://www.biorxiv.org/content/biorxiv/early/2024/01/15/2024.01.14.575607/F1.medium.gif
  buttons:
    - type: pdf
      text: Preprint
      link: https://www.biorxiv.org/content/10.1101/2024.01.14.575607v1.full.pdf
    - type: source
      text: Analysis
      link: https://zenodo.org/records/13839817
    - type: data
      text: Raw data
      link: https://zenodo.org/records/13839540
    - type: plasmid
      text: Plasmid maps
      link: https://zenodo.org/records/10547132
  tags:
    - SHIFTiKO
    - method
    - rhomboid proteases

- id: doi:10.1128/mbio.01718-23
  type: paper
  description: This paper describes the function of a patatin-like phospholipase 2 (PF3D7_1358000) in *P. falciparum*.
  image: https://journals.asm.org/cms/asset/25592b1d-c200-4ee6-b261-cb5d62192dfe/mbio.2024.15.issue-6.largecover.jpg
  buttons:
    - type: pdf
      text: Paper
      link: https://journals.asm.org/doi/pdf/10.1128/mbio.01718-23?download=true
  tags:
    - DiCre
    - phospholipases

- id: doi:10.1128/mbio.01413-23
  type: paper
  description: This paper describes a global knockout screen of phospholipases and the function of a phosphoinositide-specific phospholipase C (PF3D7_1013500) in *P. falciparum*.
  image: https://journals.asm.org/cms/10.1128/mbio.01413-23/asset/65440d7b-b82b-4313-ad1b-b9ce726ccd06/assets/images/large/mbio.01413-23.f001.jpg
  buttons:
    - type: pdf
      text: Paper
      link: https://journals.asm.org/doi/pdf/10.1128/mbio.01413-23?download=true
  tags:
    - DiCre
    - phospholipases

- id: pmid:37352369
  remove: true

- id: doi:10.1371/journal.ppat.1011449
  type: paper
  description: This paper describes the functions of perforin-like proteins and a lecithin:cholesterol acyltransferase (PF3D7_0629300) in *P. falciparum*.
  title: A malaria parasite phospholipase facilitates efficient asexual blood stage
    egress.
  authors:
  - Abhinay Ramaprasad
  - Paul-Christian Burda
  - Konstantinos Koussis
  - James A Thomas
  - Emma Pietsch
  - Enrica Calvani
  - Steven A Howell
  - James I MacRae
  - Ambrosius P Snijders
  - Tim-Wolf Gilberger
  - Michael J Blackman
  publisher: PLoS pathogens
  date: '2023-06-23'
  link: https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1011449
  abhinay-ramaprasad: true
  image: https://journals.plos.org/plospathogens/article/figure/image?size=large&id=10.1371/journal.ppat.1011449.g006
  buttons:
    - type: pdf
      text: Paper
      link: https://journals.plos.org/plospathogens/article/file?id=10.1371/journal.ppat.1011449&type=printable
    - type: source
      text: Analysis
      link: https://github.com/a2g1n/LCATxcute
    - type: docs
      text: RNotebook
      link: https://abbhinay.shinyapps.io/LCATxcute/
  tags:
    - DiCre
    - phospholipases
    - perforin-like proteins

- id: doi:10.7554/eLife.82207
  type: paper
  description: This paper describes the function of a phosphodiester glycerophosphodiesterase (PF3D7_1406300) in *P. falciparum*.
  image: https://iiif.elifesciences.org/digests/82207%2Fdigest-82207.jpg/full/617,/0/default.webp
  buttons:
    - type: pdf
      text: Paper
      link: https://elifesciences.org/download/aHR0cHM6Ly9jZG4uZWxpZmVzY2llbmNlcy5vcmcvYXJ0aWNsZXMvODIyMDcvZWxpZmUtODIyMDctdjIucGRmP2Nhbm9uaWNhbFVyaT1odHRwczovL2VsaWZlc2NpZW5jZXMub3JnL2FydGljbGVzLzgyMjA3/elife-82207-v2.pdf?_hash=GenIKuhta987ISgXDYQ2xM4vvNliWQengKFO7%2BMvDeg%3D
    - type: source
      text: Analysis
      link: https://github.com/a2g1n/GDPDxcute
    - type: docs
      text: RNotebook
      link: https://abbhinay.shinyapps.io/GDPD/
  tags:
    - DiCre
    - glycerophosphodiesterase

- id: pmid:35401459
  remove: true

- id: doi:10.3389/fmicb.2022.839524
  type: paper
  title: Pangenome Analysis of the Soilborne Fungal Phytopathogen *Rhizoctonia solani* and Development of a Comprehensive Web Resource: RsolaniDB
  authors:
  - Abhinav Kaushik
  - Daniel P Roberts
  - Abhinay Ramaprasad
  - Sara Mfarrej
  - Mridul Nair
  - Dilip K Lakshman
  - Arnab Pain
  publisher: Frontiers in microbiology
  date: '2022-03-25'
  link: https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2022.839524/full
  abhinay-ramaprasad: true
  image: https://www.frontiersin.org/files/Articles/839524/fmicb-13-839524-HTML-r1/image_m/fmicb-13-839524-g001.jpg
  buttons:
    - type: pdf
      text: Paper
      link: https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2022.839524/pdf

- id: doi:10.1186/s12915-021-00995-5
  type: paper
  title: Plasmodium vinckei genomes provide insights into the pan-genome and evolution
    of rodent malaria parasites
  description: This paper describes a genetic resource for the rodent malaria parasite *P. vinckei*.
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12915-021-00995-5/MediaObjects/12915_2021_995_Fig2_HTML.png?as=webp
  buttons:
    - type: pdf
      text: Paper
      link: https://bmcbiol.biomedcentral.com/counter/pdf/10.1186/s12915-021-00995-5.pdf
    - type: article
      text: Commentary
      link: https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-021-01019-y
    - type: data
      text: phylogenies (iTOL)
      link: https://itol.embl.de/shared/2lCr6w0mdDENs
    - type: data
      text: Raw data (ENA)
      link: https://www.ebi.ac.uk/ena/browser/view/PRJEB19355
    - type: data
      text: Genomes & Transcriptomes (PlasmoDB)
      link: https://plasmodb.org/plasmo/app/record/dataset/DS_649c2a1004
  tags:
    - genomes
 
