- id: doi:10.17504/protocols.io.eq2ly68begx9/v1
  type: protocols
  publisher: protocols.io
  title: Design strategy for DiCre-mediated inducible gene knockout in the malaria parasite
  description: This protocol describes a detailed strategy for inducibly knocking out a target gene in Plasmodium species using the Dimerisable Cre (DiCre) recombinase system, with a primary focus on *Plasmodium falciparum*.
  authors:
  - Anagha Rajesh Salvi
  - Abhinay Ramaprasad
  image: https://content.protocols.io/files/sg94cdmmp.jpg
  tags:
    - DiCre
    - protocols
  date: '2024-12-24'
  link: https://dx.doi.org/10.17504/protocols.io.eq2ly68begx9/v1

- id: doi:10.17504/protocols.io.n2bvjn9d5gk5/v1
  type: protocols
  publisher: protocols.io
  description: This protocol describes a one-pot GoldenGate assembly of a new dual-guide targeting plasmid (pCas9-Duo) expressing two distinct guide RNAs in order to enhance the chances of a successful Cas9-mediated modification at a target region in *Plasmodium falciparum*.
  image: https://protocols-files.s3.amazonaws.com/files/qssucdmmp.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJYFAX46LHRVQMGOA%2F20241225%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241225T210932Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=dba1d8be3cfcb7bcbca2e927c742f98fd0acb1918a526957262d5c80bcd543d5
  tags:
    - SHIFTiKO
    - DiCre
    - protocols

- id: doi:10.1101/2024.01.14.575607
  type: preprint
  publisher: bioRxiv
  description: This preprint introduces SHIFTiKO, a novel inducible gene knockout 
                system to study essential gene function at scale in *P. falciparum*.
  image: https://www.biorxiv.org/content/biorxiv/early/2024/01/15/2024.01.14.575607/F1.medium.gif
  buttons:
    - type: pdf
      text: Preprint
      link: https://www.biorxiv.org/content/10.1101/2024.01.14.575607v1.full.pdf
    - type: source
      text: Analysis
      link: https://zenodo.org/records/13839817
    - type: data
      text: Raw data
      link: https://zenodo.org/records/13839540
    - type: plasmid
      text: Plasmid maps
      link: https://zenodo.org/records/10547132
  tags:
    - SHIFTiKO
    - method
    - rhomboid proteases

- id: doi:10.1128/mbio.01718-23
  type: paper
  description: This paper describes the function of a patatin-like phospholipase 2 (PF3D7_1358000) in *P. falciparum*.
  image: https://journals.asm.org/cms/asset/25592b1d-c200-4ee6-b261-cb5d62192dfe/mbio.2024.15.issue-6.largecover.jpg
  buttons:
    - type: pdf
      text: Paper
      link: https://journals.asm.org/doi/pdf/10.1128/mbio.01718-23?download=true
  tags:
    - DiCre
    - phospholipases

- id: doi:10.1128/mbio.01413-23
  type: paper
  description: This paper describes a global knockout screen of phospholipases and the function of a phosphoinositide-specific phospholipase C (PF3D7_1013500) in *P. falciparum*.
  image: https://journals.asm.org/cms/10.1128/mbio.01413-23/asset/65440d7b-b82b-4313-ad1b-b9ce726ccd06/assets/images/large/mbio.01413-23.f001.jpg
  buttons:
    - type: pdf
      text: Paper
      link: https://journals.asm.org/doi/pdf/10.1128/mbio.01413-23?download=true
  tags:
    - DiCre
    - phospholipases

- id: pmid:37352369
  remove: true

- id: doi:10.1371/journal.ppat.1011449
  type: paper
  description: This paper describes the functions of perforin-like proteins and a lecithin:cholesterol acyltransferase (PF3D7_0629300) in *P. falciparum*.
  title: A malaria parasite phospholipase facilitates efficient asexual blood stage
    egress.
  authors:
  - Abhinay Ramaprasad
  - Paul-Christian Burda
  - Konstantinos Koussis
  - James A Thomas
  - Emma Pietsch
  - Enrica Calvani
  - Steven A Howell
  - James I MacRae
  - Ambrosius P Snijders
  - Tim-Wolf Gilberger
  - Michael J Blackman
  publisher: PLoS pathogens
  date: '2023-06-23'
  link: https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1011449
  abhinay-ramaprasad: true
  image: https://journals.plos.org/plospathogens/article/figure/image?size=large&id=10.1371/journal.ppat.1011449.g006
  buttons:
    - type: pdf
      text: Paper
      link: https://journals.plos.org/plospathogens/article/file?id=10.1371/journal.ppat.1011449&type=printable
    - type: source
      text: Analysis
      link: https://github.com/a2g1n/LCATxcute
    - type: docs
      text: RNotebook
      link: https://abbhinay.shinyapps.io/LCATxcute/
  tags:
    - DiCre
    - phospholipases
    - perforin-like proteins

- id: doi:10.7554/eLife.82207
  type: paper
  description: This paper describes the function of a phosphodiester glycerophosphodiesterase (PF3D7_1406300) in *P. falciparum*.
  image: https://iiif.elifesciences.org/digests/82207%2Fdigest-82207.jpg/full/617,/0/default.webp
  buttons:
    - type: pdf
      text: Paper
      link: https://elifesciences.org/download/aHR0cHM6Ly9jZG4uZWxpZmVzY2llbmNlcy5vcmcvYXJ0aWNsZXMvODIyMDcvZWxpZmUtODIyMDctdjIucGRmP2Nhbm9uaWNhbFVyaT1odHRwczovL2VsaWZlc2NpZW5jZXMub3JnL2FydGljbGVzLzgyMjA3/elife-82207-v2.pdf?_hash=GenIKuhta987ISgXDYQ2xM4vvNliWQengKFO7%2BMvDeg%3D
    - type: source
      text: Analysis
      link: https://github.com/a2g1n/GDPDxcute
    - type: docs
      text: RNotebook
      link: https://abbhinay.shinyapps.io/GDPD/
  tags:
    - DiCre
    - glycerophosphodiesterase

- id: pmid:35401459
  remove: true

- id: doi:10.3389/fmicb.2022.839524
  type: paper
  title: Pangenome analysis of the soilborne fungal phytopathogen <i>Rhizoctonia solani</i> and development of a comprehensive web resource - RsolaniDB
  authors:
  - Abhinav Kaushik
  - Daniel P Roberts
  - Abhinay Ramaprasad
  - Sara Mfarrej
  - Mridul Nair
  - Dilip K Lakshman
  - Arnab Pain
  publisher: Frontiers in microbiology
  date: '2022-03-25'
  link: https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2022.839524/full
  buttons:
    - type: pdf
      text: Paper
      link: https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2022.839524/pdf

- id: doi:10.1186/s12915-021-00995-5
  type: paper
  title: Plasmodium vinckei genomes provide insights into the pan-genome and evolution
    of rodent malaria parasites
  description: This paper describes a genetic resource for the rodent malaria parasite *P. vinckei*.
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12915-021-00995-5/MediaObjects/12915_2021_995_Fig2_HTML.png?
  buttons:
    - type: pdf
      text: Paper
      link: https://bmcbiol.biomedcentral.com/counter/pdf/10.1186/s12915-021-00995-5.pdf
    - type: article
      text: Commentary
      link: https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-021-01019-y
    - type: data
      text: Genomes & Transcriptomes (PlasmoDB)
      link: https://plasmodb.org/plasmo/app/record/dataset/DS_649c2a1004
    - type: data
      text: Raw data (ENA)
      link: https://www.ebi.ac.uk/ena/browser/view/PRJEB19355
    - type: data
      text: phylogenies (iTOL)
      link: https://itol.embl.de/shared/2lCr6w0mdDENs
  tags:
    - genomes
    - transcriptomics
    - rodent malaria model
    - NGS
 
- id: pmid:33902581
  remove: true

- id: doi:10.1186/s12916-021-01982-x
  title: Estimating the effectiveness of routine asymptomatic PCR testing at different
    frequencies for the detection of SARS-CoV-2 infections.
  authors:
  - Joel Hellewell
  - Timothy W Russell
  - The SAFER Investigators and Field Study Team
  - The Crick COVID-19 Consortium
  - CMMID COVID-19 working group
  - Rupert Beale
  - Gavin Kelly
  - Catherine Houlihan
  - Eleni Nastouli
  - Adam J Kucharski
  publisher: BMC medicine
  date: '2021-04-27'
  link: https://bmcmedicine.biomedcentral.com/articles/10.1186/s12916-021-01982-x
  buttons:
    - type: pdf
      text: Paper
      link: https://bmcmedicine.biomedcentral.com/counter/pdf/10.1186/s12916-021-01982-x.pdf
  tags:
    - covid-19

- id: doi:10.3390/cells9122590
  title: MRE11 is crucial for malaria parasite transmission and its absence affects expression of interconnected networks of key genes essential for life
  link: https://bmcmedicine.biomedcentral.com/articles/10.1186/s12916-021-01982-x
  image: https://www.mdpi.com/cells/cells-09-02590/article_deploy/html/images/cells-09-02590-g004.png
  buttons:
    - type: pdf
      text: Paper
      link: https://www.mdpi.com/2073-4409/9/12/2590/pdf?version=1607085536
  tags:
    - transcriptomics
    - rodent malaria model
    - NGS

- id: pmid:33279440
  remove: true

- id: 10.1016/j.yebeh.2020.107602
  title: Clinical outcomes of COVID-19 in long-term care facilities for people with
    epilepsy.
  authors:
  - Simona Balestrini
  - Matthias J Koepp
  - Sonia Gandhi
  - Hannah M Rickman
  - Gee Yen Shin
  - Catherine F Houlihan
  - Jonny Anders-Cannon
  - Katri Silvennoinen
  - Fenglai Xiao
  - Sara Zagaglia
  - Kirsty Hudgell
  - Mariusz Ziomek
  - Paul Haimes
  - Adam Sampson
  - Annie Parker
  - J Helen Cross
  - Rosemarie Pardington
  - Eleni Nastouli
  - Charles Swanton
  - Josemir W Sander
  - Sanjay M Sisodiya
  - Crick COVID Consortium
  publisher: 'Epilepsy & Behavior'
  date: '2020-11-05'
  link: https://www.sciencedirect.com/science/article/pii/S1525505020307824
  buttons:
    - type: pdf
      text: Paper
      link: https://pdf.sciencedirectassets.com/272395/1-s2.0-S1525505020X00163/1-s2.0-S1525505020307824/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEFUaCXVzLWVhc3QtMSJIMEYCIQD4%2BNiQhHHvzzny%2FcCTjDa1h5uJBVOq7oXeZxgogpClRgIhAKjjO0aqiyl%2BMXO7GYb2QUv%2BtZE7ZDQiwQeBuOOyQbZLKrMFCC0QBRoMMDU5MDAzNTQ2ODY1Igzm5VH6IeLtFvTubcQqkAX52%2F9BgW4hE%2B%2FZLi3ciRrRF7yeqQonHG6agIPSsvMVZlt3ici6PK%2BRH3btoPIjwdmpnIJFxdXVjRSI1VtugJ28xBWz8yUgQ35PzzNMbKJb2YTd6ZLq4SwR36AwltJSZBmwbpzMbpDVg94DlPOtC6FL2RDGoGJd5WcH1ILD4DfEOVGbPK9IZJn1vM%2BSBGVAec9iIy2nAEbACrzHT8WAfEXFX6qOegvN31jvenUhi430MsYbrnuIfHhh2dElLoCYlhwecMX3WsBE9W77CXqtNTGEQ8V45f1f1Fll6GAc4%2BrM4PaCkEqmtxs12jlYPj7XlWixveE4DKyjFir5Wq33SPrWuOlLv%2Bn99khcogY6ekT6xfNraDmmStNXUvw1yIGK4IbH7Ly8nf0X3pmjhu8hK8wXwAPwnALG9uU7vdIkReojmnpjN0Y1elHQO%2FHPhLlw06iyYL3TVt8o%2Bmnq7L0ueyueUYBtm8Iw9CevT%2FFVTszcgT%2FCORB%2Ftwk6uQl9uUJTy64F%2F8thaXrkm7RexrXtUakIwgBla3slgCk%2FYOdPHZbs6UbiK%2FxdHn%2BOKXfTvZu9IedXGPeeiXPJfsuIGWyjid8IhyqXODmPiRhfJNtn8Y10L3Ok1Im6fp8ia2UotRHvvvTruQ%2FSLIEyYu7NUtOaYDUEh86BjouR57GyElqn5YThxOhqLTBi%2BGI1YyoWeOxycbDWefFlV9tBCHuZKC2%2B8YBivNbeCH7wRQsJMrFHx%2FFmzsadhKjT2HmdspdRHzYUpgUDVy9ivoTHfust%2FGO7otlzBNn5pRaVzxon3dt1ZtWRJ6BLczhjjjsYv8kJkFAObC0%2FzddlR0%2BR211WxOtk%2F5hm2C9P1qIY%2F4Bu1YtyQ7u%2BXjC5kbW7BjqwAUckrnLQlMYycG3tsOyC3jue4yTd12VqdcwbXRSaPuSInT%2B2LrZUCtpYK3Wb4V%2Ft%2F1HfAPEElxTwIGXMMhyb2islThNS2Y3hmCHBKHO%2BFnSnikDIkyA%2FD9UwE%2BP03j85lV%2FwJXm1CwRihaJfbbanKvONONqetcbuzFOt4TrWVPWTTLjj0RoNz5gwAKx1Ckvnp7U2Dl9TgwDCAE3aAZZC7XKISeqmUaiCezldm6r5RXT7&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241226T131529Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTY6Y4UWHCS%2F20241226%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=85aaacd8eb6ffb54ed86ed25e220f07e4c8f293831e2fe67c9a24c70bc68fb7a&hash=1a3f0a8d9426eea8eb50a5d884ba911304ddc16da68c47dd6d49bdc4ef07efba&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S1525505020307824&tid=spdf-3f66ddde-b0f9-45d2-a4af-5890ba925540&sid=4ecccfda38bba44e393bc750219d5a34b15agxrqb&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=1d045d095b565a59565a56&rr=8f8157053e52952c&cc=gb
  tags:
    - covid-19

- id: doi:10.1101/2020.09.07.286369
  remove: true

- id: pmid:32555528
  remove: true

- id: doi:10.1038/s41587-020-0588-y
  title: Scalable and robust SARS-CoV-2 testing in an academic center.
  authors:
  - Jim Aitken
  - Karen Ambrose
  - Sam Barrell
  - Rupert Beale
  - Ganka Bineva-Todd
  - Dhruva Biswas
  - Richard Byrne
  - Simon Caidan
  - Peter Cherepanov
  - Laura Churchward
  - Graham Clark
  - Margaret Crawford
  - Laura Cubitt
  - Vicky Dearing
  - Christopher Earl
  - Amelia Edwards
  - Chris Ekin
  - Efthymios Fidanis
  - Alessandra Gaiba
  - Steve Gamblin
  - Sonia Gandhi
  - Jacki Goldman
  - Robert Goldstone
  - Paul R Grant
  - Maria Greco
  - Judith Heaney
  - Steve Hindmarsh
  - Catherine F Houlihan
  - Michael Howell
  - Michael Hubank
  - Deborah Hughes
  - Rachael Instrell
  - Deborah Jackson
  - Mariam Jamal-Hanjani
  - Ming Jiang
  - Mark Johnson
  - Leigh Jones
  - Nnennaya Kanu
  - George Kassiotis
  - Stuart Kirk
  - Svend Kjaer
  - Andrew Levett
  - Lisa Levett
  - Marcel Levi
  - Wei-Ting Lu
  - James I MacRae
  - John Matthews
  - Laura E McCoy
  - Catherine Moore
  - David Moore
  - Eleni Nastouli
  - Jerome Nicod
  - Luke Nightingale
  - Jessica Olsen
  - Nicola O'Reilly
  - Amar Pabari
  - Venizelos Papayannopoulos
  - Namita Patel
  - Nigel Peat
  - Marc Pollitt
  - Peter Ratcliffe
  - Caetano Reis e Sousa
  - Annachiara Rosa
  - Rachel Rosenthal
  - Chloe Roustan
  - Andrew Rowan
  - Gee Yen Shin
  - Daniel M Snell
  - Ok-Ryul Song
  - Moira J Spyer
  - Amy Strange
  - Charles Swanton
  - James M A Turner
  - Melanie Turner
  - Andreas Wack
  - Philip A Walker
  - Sophia Ward
  - Wai Keong Wong
  - Joshua Wright
  - Mary Wu
  - Crick COVID Consortium
  publisher: Nature biotechnology
  date: '2020-08-01'
  link: https://www.nature.com/articles/s41587-020-0588-y
  buttons:
    - type: pdf
      text: Paper
      link: https://www.nature.com/articles/s41587-020-0588-y.pdf
  tags:
    - covid-19

- id: pmid:32653078
  remove: true

- id: doi:10.1016/S0140-6736(20)31484-7 
  title: Pandemic peak SARS-CoV-2 infection and seroconversion rates in London frontline health-care workers.
  authors:
  - Catherine F Houlihan
  - Nina Vora
  - Thomas Byrne
  - Dan Lewer
  - Gavin Kelly
  - Judith Heaney
  - Sonia Gandhi
  - Moira J Spyer
  - Rupert Beale
  - Peter Cherepanov
  - David Moore
  - Richard Gilson
  - Steve Gamblin
  - George Kassiotis
  - Laura E McCoy
  - Charles Swanton
  - Crick COVID Consortium
  - Andrew Hayward
  - Eleni Nastouli
  - SAFER Investigators
  publisher: Lancet
  date: '2020-07-09'
  link: https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31484-7/fulltext
  buttons:
    - type: pdf
      text: Paper
      link: https://www.thelancet.com/action/showPdf?pii=S0140-6736%2820%2931484-7
  tags:
    - covid-19

- id: doi:10.1038/s41467-020-16593-y
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-020-16593-y/MediaObjects/41467_2020_16593_Fig3_HTML.png
  buttons:
    - type: pdf
      text: Paper
      link: https://www.nature.com/articles/s41467-020-16593-y.pdf
  tags:
    - transcriptomics
    - gene knockout
    - rodent malaria model
    - NGS

- id: doi:10.1038/s41598-019-46398-z
  buttons:
    - type: pdf
      text: Paper
      link: https://www.nature.com/articles/s41598-019-46398-z.pdf
  tags:
    - NGS

- id: doi:10.1186/s12936-018-2487-y
  buttons:
    - type: pdf
      text: Paper
      link: https://malariajournal.biomedcentral.com/counter/pdf/10.1186/s12936-018-2487-y.pdf
  tags:
    - proteomics

- id: doi:10.1101/350546
  remove: true

- id: 10.1186/s12936-019-2659-4
  title: A fast and cost-effective microsampling protocol incorporating reduced animal usage for time-series transcriptomics in rodent malaria parasites.
  authors:
  - Abhinay Ramaprasad
  - Amit Kumar Subudhi
  - Richard Culleton
  - Arnab Pain
  publisher: Malaria Journal
  date: '2019-01-25'
  link: https://malariajournal.biomedcentral.com/articles/10.1186/s12936-019-2659-4
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12936-019-2659-4/MediaObjects/12936_2019_2659_Fig1_HTML.png
  buttons:
    - type: pdf
      text: Paper
      link: https://malariajournal.biomedcentral.com/counter/pdf/10.1186/s12936-019-2659-4.pdf
  tags:
    - transcriptomics
    - rodent malaria model
    - NGS

- id: doi:10.1371/journal.ppat.1006900
  buttons:
    - type: pdf
      text: Paper
      link: https://journals.plos.org/plospathogens/article/file?id=10.1371/journal.ppat.1006900&type=printable
  tags:
    - rodent malaria model

- id: doi:10.1371/journal.ppat.1006447
  buttons:
    - type: pdf
      text: Paper
      link: https://journals.plos.org/plospathogens/article/file?id=10.1371/journal.ppat.1006447&type=printable
  tags:
    - rodent malaria model

- id: pmid:28225668
  remove: true

- id: doi:10.1056/NEJMc1612765
  title: Emergence of indigenous artemisinin-resistant Plasmodium falciparum in Africa.
  authors:
  - Feng Lu
  - Richard Culleton
  - Meihua Zhang
  - Abhinay Ramaprasad
  - Lorenz von Seidlein
  - Huayun Zhou
  - Guoding Zhu
  - Jianxia Tang
  - Yaobao Liu
  - Weiming Wang
  - Yuanyuan Cao
  - Sui Xu
  - Yaping Gu
  - Julin Li
  - Chao Zhang
  - Qi Gao
  - Didier Menard
  - Arnab Pain
  - Haitao Yang
  - Qingfeng Zhang
  - Jun Cao
  publisher: The New England Journal of Medicine
  date: '2017-02-22'
  link: https://www.nejm.org/doi/full/10.1056/NEJMc1612765
  image: https://www.nejm.org/cms/10.1056/NEJMc1612765/asset/9561f1ab-0e0c-45a7-93c2-af88423d7366/assets/images/large/nejmc1612765_f1.jpg
  buttons:
    - type: pdf
      text: Paper
      link: https://www.nejm.org/doi/pdf/10.1056/NEJMc1612765
  tags:
    - NGS
- id: doi:10.1016/j.ijpara.2016.05.009  
