- id: doi:10.17504/protocols.io.n2bvjn9d5gk5/v1
  type: protocols
  publisher: protocols.io
  description: This protocol describes a one-pot GoldenGate assembly of a new dual-guide targeting plasmid (pCas9-Duo) expressing two distinct guide RNAs in order to enhance the chances of a successful Cas9-mediated modification at a target region in *Plasmodium falciparum*.
  image: https://protocols-files.s3.amazonaws.com/files/qssucdmmp.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJYFAX46LHRVQMGOA%2F20241225%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241225T210932Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=dba1d8be3cfcb7bcbca2e927c742f98fd0acb1918a526957262d5c80bcd543d5
  tags:
    - SHIFTiKO
    - DiCre
    - protocols

- id: doi:10.1101/2024.01.14.575607
  type: preprint
  publisher: bioRxiv
  description: This preprint introduces SHIFTiKO, a novel inducible gene knockout 
                system to study essential gene function at scale in *P. falciparum*.
  image: https://www.biorxiv.org/content/biorxiv/early/2024/01/15/2024.01.14.575607/F1.medium.gif
  buttons:
    - type: pdf
      text: Preprint
      link: https://www.biorxiv.org/content/10.1101/2024.01.14.575607v1.full.pdf
    - type: source
      text: Analysis
      link: https://zenodo.org/records/13839817
    - type: data
      text: Raw data
      link: https://zenodo.org/records/13839540
    - type: plasmid
      text: Plasmid maps
      link: https://zenodo.org/records/10547132
  tags:
    - SHIFTiKO
    - DiCre
    - method
    - rhomboid proteases

- id: doi:10.1128/mbio.01718-23
  type: paper
  description: This paper describes the function of a patatin-like phospholipase 2 (PF3D7_1358000) in *P. falciparum*.
  image: https://journals.asm.org/cms/asset/25592b1d-c200-4ee6-b261-cb5d62192dfe/mbio.2024.15.issue-6.largecover.jpg
  buttons:
    - type: pdf
      text: Paper
      link: https://journals.asm.org/doi/pdf/10.1128/mbio.01718-23?download=true
  tags:
    - collaboration
    - DiCre
    - phospholipases
